### ISSUE TITLE
version on maven repos does not contains latest updates

### ISSUE THREAD

**Issue by TLavocat** [zeromq/jzmq-api#40]
Hi,

On the 0.1.0-SNAPSHOT on https://oss.sonatype.org/content/repositories/snapshots it is not possible to use the class org.zeromq-api.Message.

Can you upload the latest version of the snapshot please ?

Thank's,
Thomas

**Comment by sjohnr** [comment]
Have you tried using the released version on maven central? It is 0.1.0.
